### ISSUE TITLE
Android 浏览器文本垂直居中问题

### ISSUE THREAD

**Issue by forColourfulLife** [forColourfulLife/notes#1]
### 问题描述
在开发中，我们经常使用`line-height`来实现文本的垂直居中，但是当字体小于12px时，大部分Android设备的浏览器文字都会稍微偏上，效果如下：

![demo](https://user-images.githubusercontent.com/9638347/53538134-61bcf100-3b47-11e9-9410-92ed059aa59a.png)

### 方案一
先将该元素的所有大小属性放大两倍，然后再通过`transform: scale(0.5)`缩小一倍。注意：缩小后的元素还是会占据原来空间，对布局会造成一定影响。

### 方案二
利用行高、对齐的关系，结合伪元素得出的黑科技，亲测效果很理想，代码如下：

```css
&::before {
    content: '';
    display: inline-block;
    vertical-align: middle;
    width: 0;
    height: 100%;
    margin-top: 1px;
}
```

效果如下：

![170bdaf1-6dfa-43f7-a814-71b991e2ae79](https://user-images.githubusercontent.com/9638347/53538715-ced18600-3b49-11e9-8ffa-ee8850abd5f0.png)
