### ISSUE TITLE
文字超出显示省略号

### ISSUE THREAD

**Issue by forColourfulLife** [forColourfulLife/notes#2]
1.在项目的公共css文件中，添加下面代码
```css
.text-ellipsis {
    display: -webkit-box;
    overflow: hidden;
    text-overflow: ellipsis;
    -webkit-box-orient: vertical;
    // 指定显示的文本的行数
    -webkit-line-clamp: 1; 
}
```
2.在对应的元素上面，添加该class，如果需要显示2行文本，就直接在该元素中添加 css `-webkit-line-clamp: 2; `
