### ISSUE TITLE
iPhone X 适配

### ISSUE THREAD

**Issue by forColourfulLife** [forColourfulLife/notes#3]
## 问题描述

iPhoneX 取消了物理按键，改成底部小黑条，这一改动导致网页出现了比较尴尬的屏幕适配问题。对于网页而言，顶部（刘海部位）的适配问题浏览器已经做了处理，所以我们只需要关注底部与小黑条的适配问题即可（即常见的吸底导航、返回顶部等各种相对底部 fixed 定位的元素）。

### 第一步：设置网页在可视窗口的布局方式

新增 viweport-fit 属性，使得页面内容完全覆盖整个窗口：

 ```html
<meta name="viewport" content="width=device-width, viewport-fit=cover">
```

### 第二步：在项目公共css文件中添加代码

```css
  /* 适配IPhone X */
  :root {
    --safe-area-inset-top: 0;
    --safe-area-inset-bottom: 0;
  }
  @supports (width: constant(safe-area-inset-top)) {
    :root {
      --safe-area-inset-top: constant(safe-area-inset-top);
      --safe-area-inset-bottom: constant(safe-area-inset-bottom);
    }
  }
  @supports (width: env(safe-area-inset-top)) {
    :root {
      --safe-area-inset-top: env(safe-area-inset-top);
      --safe-area-inset-bottom: env(safe-area-inset-bottom);
    }
  }
```

### 第三步：在底部固定元素上增加css

可以通过加内边距 padding 扩展高度：

```css
padding-bottom: var(--safe-area-inset-bottom)
```

或者通过计算函数 calc 覆盖原来高度：

```
height: calc(60px + var(--safe-area-inset-bottom));
```
